version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ${PWD}:/app
    ports:
      - ${DOCKER_APP_PUBLISHING_PORT}:${APP_PORT}
    networks:
      - mtproject
    env_file: .env

networks:
  mtproject:
    external: true
